ImportFunc;0;env;changeTable
ImportFunc;1;env;changeTable2
ImportFunc;2;env;a
ImportFunc;3;env;b
ExportCall;main;
ImportCall;2;a
ImportReturn;2;a;1
ImportCall;0;changeTable
ImportReturn;0;changeTable;
TableGet;0;table;0;16;foo
ImportCall;1;changeTable2
ImportReturn;1;changeTable2;
TableGet;0;table;0;17;bar
