ImportFunc;0;env;changeMemAfterReentry
ImportFunc;1;env;changeMemBeforeReentry
ExportCall;main;
ImportCall;0;changeMemAfterReentry
ExportCall;reentry;
ImportReturn;0;changeMemAfterReentry;
Load;0;memory;1;1,0,0,0
ImportCall;1;changeMemBeforeReentry
ExportCall;reentry;
Load;0;memory;1;1,0,0,0
ImportReturn;1;changeMemBeforeReentry;
