ImportFunc;0;env;add
ExportCall;main;1,2
ImportCall;0;add
ImportReturn;0;add;4
ImportCall;0;add
ImportReturn;0;add;9
ImportCall;0;add
ImportReturn;0;add;5
ExportCall;main;3,2
ImportCall;0;add
ImportReturn;0;add;4
ImportCall;0;add
ImportReturn;0;add;9
ImportCall;0;add
ImportReturn;0;add;5
ExportCall;main;4,4
ImportCall;0;add
ImportReturn;0;add;8
ImportCall;0;add
ImportReturn;0;add;13
ImportCall;0;add
ImportReturn;0;add;9
