ImportFunc;0;env;changeMemAfterReentry
ImportFunc;1;env;changeMemBeforeReentry
ImportFunc;2;env;foo
ImportFunc;3;env;bar
ExportCall;main;
ImportCall;0;changeMemAfterReentry
ExportCall;reentry;
ImportCall;2;foo
ExportCall;reentry2;
ImportCall;3;bar
ImportReturn;3;bar;
ImportReturn;2;foo;
ImportReturn;0;changeMemAfterReentry;
Load;0;memory;1;1,0,0,0
ImportCall;1;changeMemBeforeReentry
ExportCall;reentry;
ImportCall;2;foo
ExportCall;reentry2;
ImportCall;3;bar
ImportReturn;3;bar;
ImportReturn;2;foo;
ImportReturn;1;changeMemBeforeReentry;
Load;0;memory;1;2,0,0,0
