ImportTable;0;env;table;2;anyfunc
ImportFunc;0;env;changeTable
ImportFunc;1;env;a
ImportFunc;2;env;b
ExportCall;main;
ImportCall;1;a
ImportReturn;1;a;1
ImportCall;0;changeTable
ImportReturn;0;changeTable;
TableGet;0;table;0;13;foo
